config/routes.rb
Quotewhat::Application.routes.draw do
  get "users/show"
  get "static_pages/home"
  get "static_pages/about"
  
  resources :pins

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'users/:id' => 'users#show', as: :user

  root to: 'pins#index'
  get '/home', to: 'static_pages#home'
  get '/about', to: 'static_pages#about'

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "320x240>" }, :default_url => "https://dl.dropboxusercontent.com/u/21093381/quotewhat/image-missing.jpg"

	validates :category, :user_id, presence: true
	validates_attachment :image, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']}, size: { less_than: 5.megabytes}

	def image_remote_url=(url_value)
		self.image = URI.parse(url_value) unless url_value.blank?
		super
	end

	def category=(s)
    super s.titleize
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable,
  				:rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  has_many :pins, :dependent => :destroy

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "https://dl.dropboxusercontent.com/u/21093381/quotewhat/avatar-missing.jpg"

  validates :username, presence: true, uniqueness: true

  validates_attachment :avatar, content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']}, size: { less_than: 5.megabytes}

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    unless user
      user = User.create(username:auth.extra.raw_info.name,
                         provider:auth.provider,
                         uid:auth.uid,
                         email:auth.info.email,
                         password:Devise.friendly_token[0,20])
    end
    user
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :configure_permitted_parameters, if: :devise_controller?

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

	  def configure_permitted_parameters
	    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:username, :first_name, :last_name, :email, :password, :password_confirmation, :avatar, :provider, :uid)}
	    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation, :current_password, :avatar, :provider, :uid)}
	  end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(30)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pin }
      else
        format.html { render action: 'new' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      if current_user.admin
        @pin = Pin.find(params[:id])
      else
        @pin = current_user.pins.find(params[:id])
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:content, :author, :category, :image, :image_remote_url)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
 	end

  def about
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"], current_user)

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.find_for_google_oauth2(request.env["omniauth.auth"], current_user)

      if @user.persisted?
        flash[:notice] = I18n.t "devise.omniauth_callbacks.success", :kind => "Google"
        sign_in_and_redirect @user, :event => :authentication
      else
        session["devise.google_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!
	
  def show
  	@user = User.find(params[:id])
    @pins = @user.pins.order("created_at desc").page(params[:page]).per_page(20)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div id="contact" class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <ul class="list-inline">
          <li><a href=""><img class="img-responsive" src="https://dl.dropboxusercontent.com/u/21093381/quotewhat/logo-facebook.png"></a></li>
          <li><a href=""><img class="img-responsive" src="https://dl.dropboxusercontent.com/u/21093381/quotewhat/logo-twitter.png"></a></li>
          <li><a href=""><img class="img-responsive" src="https://dl.dropboxusercontent.com/u/21093381/quotewhat/logo-googleplus.png"></a></li>
        </ul>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center contact-text">
        <h4>Got more questions? Email us.</h4>
        <a href="mailto:support@quotewhat.com">support@quotewhat.com</a>
        <hr>
        <p>Copyright &copy; QuoteWhat 2013</p>
      </div>
    </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Navigation Bar -->
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a href="/pins" class="navbar-brand">"Quote"What?</a>
  </div>
  <!-- Collapsed Navigation Bar -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
  <!-- If the user is signed in, display the following  -->
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Quotes Universe", pins_path %></li>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Search By<b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><a href="">Authors</a></li>
            <li><a href="">Categories</a></li>
            <li><a href="">Picture Quotes</a></li>
          </ul>
        </li>
        <li><%= link_to "About Us", about_path %></li>
        <li id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "My Profile", current_user %></li>
            <li><%= link_to "My Setting", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
      <div class="navbar-form navbar-right">
        <%= link_to "Add Quote", new_pin_path, class: "btn btn-success" %>
      </div>
    <!-- If the user is not signed in, display the following -->
    <% else %>
      <div class="navbar-form navbar-right">
        <%= link_to "Sign In", new_user_session_path, class: "btn btn-default" %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="">Authors</a></li>
        <li><a href="">Categories</a></li>
        <li><a href="">Picture Quotes</a></li>
      </ul>
    <% end %>
  </div> <!-- / Collapsed Navigation Bar -->
</nav> <!-- / Navigation Bar -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteWhat | <%= yield :title %></title>
    <link rel="shortcut icon" type="image/x-icon" href="https://dl.dropboxusercontent.com/u/21093381/quotewhat/quote.ico">
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= render 'layouts/shim' %>
    <%= csrf_meta_tags %>
    <%= tag :meta, name: "viewport", content: "width=device-width,initial-scale=1.0" %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |key, value| %>
      <div class="alert alert-success" style="margin-bottom: 0px">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= value %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pins/_add_button.html.erb
<div class="btn-group">
  <a class="btn btn-success dropdown-toggle" data-toggle="dropdown" href="#">Add</a>
  <ul class="dropdown-menu">
    <li><a class="passport button_text">My Passport</a></li>
    <li><a class="travel_plans button_text">Travel Plans</a></li>
    <li><a class="destination_wishlist button_text">Destination Wishlist</a></li>
  </ul>
</div>

app/views/pins/_form.html.erb
<div class="panel-body">
	<%= form_for(@pin) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, rows: "5", placeholder: "I have no special talent.  I am only passionately curious.", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, placeholder: "Albert Einstein", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.select(:category, options_for_select([['Love', 'love'], ['Humor', 'humor']], "love"), {}, {class: "form-control"}) %>
  </div>
  <h3>Upload a Picture Quote</h3>
  <hr>
	<div class="form-group">
		<%= f.label :image, "From Computer" %>
		<%= f.file_field :image, class: "form-control" %>
	</div>
  <div class="form-group">
  	<%= f.label :image_remote_url, "From Website" %>
  	<%= f.text_field :image_remote_url, placeholder: "http://prettypic.com/mountain.jpg", class: "form-control" %>
	</div>
	<div class="form-group">
  	<%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
	</div>
</div>

app/views/pins/_pin.html.erb
<div class="box">
	<% if pin.user != current_user %>
		<div class="add_button">
			<%= render 'pins/add_button' %>
		</div>
		<button class="btn btn-danger like_button">Like</button>
	<% end %>
	<a href="#<%= pin.id %>"><%= image_tag pin.image(:medium) %></a>
  <p class="pin_text content"><%= pin.content %> - <%= pin.author %></p>
  <p class="pin_text"><strong>Category: </strong><%= pin.category %> - 
		<% if (current_user == pin.user) || (current_user.admin) %>
		  	<%= link_to 'Edit', edit_pin_path(pin) %>
		<% end %>
	</p>
</div>

app/views/pins/edit.html.erb
<% provide(:title, 'Edit Pin') %>
<div class="container edit_pin">
  <div class="row">
    <div class="col-md-7 col-md-offset-2">
    	<div class="panel panel-default">
    		<div class="panel-heading">
    			<h1>Editing pin</h1>
    		</div>
	    	<div class="panel-body">
	    		<%= render 'form' %>
					<%= link_to 'Show', @pin %> |
					<%= link_to 'Your Profile', current_user %>
				</div>
				<div class="panel-footer">
					<h5>Not a Good Pin? <br/><br/> <%= button_to "Delete Pin", pin_path(@pin), :data => { :confirm => "Are you sure? No turning back if you press the button!" }, class: "btn btn-danger", :method => :delete %></h5>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pins/index.html.erb
<!-- Render the Homepage if the User is not signed in -->
<%= render 'static_pages/home' unless user_signed_in? %>

<!-- Render the Index Page if the user is signed in -->
<% provide(:title, 'Destinations') %>
<!-- Index Pin Header -->
<div id="indexheader">
	<div id="indexheader-text">
		<h1>Every <span><em>New Destination</em></span> is a <span><em>New Experience</em></span></h1>
	</div>
</div>
<!-- /Index Pin Header  -->
<div class="index-container">
	<!-- Left Content - All Quotes -->
	<div class="row">
		<div class="col-md-9">
			<!-- Display All Pins -->
		  <div id="masonry-container", class="transitions-enabled infinite-scroll clearfix">
		    <%= render @pins %>
		  </div>
		  <%= will_paginate @pins %>
		</div> <!-- End of Left Content -->
		<!-- Right Content - Search Bar, Categories, Ad -->
		<div class="col-md-3">
			<!-- Keyword Search -->
			<div class="well index-well" style="margin-top: 10px">
        <h4>Quote Search</h4>
        <%= form_tag(pins_path, :method => "get") do %>
          <div class="input-group">
            <%= text_field_tag :search, params[:search], class: "form-control search-bar", placeholder: "Search Quotes" %>
            <div class="input-group-btn">
              <button class="btn btn-default search-btn" type="submit">Search</button>
            </div>
          </div>
        <% end %>
      </div> 
      <!-- Search By Popular Authors -->
      <div class="well index-well">
        <h4>Popular Authors</h4>
        <div class="row">
          <div class="col-md-6">
            <ul class="list-unstyled">
              <li><a href="#dinosaurs">Dinosaurs</a></li>
              <li><a href="#spaceships">Spaceships</a></li>
              <li><a href="#fried-foods">Fried Foods</a></li>
              <li><a href="#wild-animals">Wild Animals</a></li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="list-unstyled">
              <li><a href="#alien-abductions">Alien Abductions</a></li>
              <li><a href="#business-casual">Business Casual</a></li>
              <li><a href="#robots">Robots</a></li>
              <li><a href="#fireworks">Fireworks</a></li>
            </ul>
          </div>
        </div>
      </div>
      <!-- Search By Popular Categories -->
      <div class="well index-well">
        <h4>Popular Categories</h4>
        <div class="row">
          <div class="col-md-6">
            <ul class="list-unstyled">
              <li><a href="#dinosaurs">Dinosaurs</a></li>
              <li><a href="#spaceships">Spaceships</a></li>
              <li><a href="#fried-foods">Fried Foods</a></li>
              <li><a href="#wild-animals">Wild Animals</a></li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="list-unstyled">
              <li><a href="#alien-abductions">Alien Abductions</a></li>
              <li><a href="#business-casual">Business Casual</a></li>
              <li><a href="#robots">Robots</a></li>
              <li><a href="#fireworks">Fireworks</a></li>
            </ul>
          </div>
        </div>
      </div> <!-- End of Popular Categories -->
    </div> <!-- End of Right Content -->
	</div> <!-- End of row -->
</div> <!-- End of index-container -->

app/views/pins/new.html.erb
<% provide(:title, 'New Pin') %>
<div class="container new_pin">
  <div class="row">
    <div class="col-md-7 col-md-offset-2">
    	<div class="panel panel-default">
				<div class="panel-heading">
					<h1>Add a New Quote<br/><small>Either a Picture Quote or Enter In the Quote</small></h1>
				</div>
				<%= render 'form' %>
				<div class="panel-footer">
				  <%= link_to 'Back', pins_path %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pins/show.html.erb
<% provide(:title, 'The Pin') %>
<div class="container show_pin">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 well">
  		<%= image_tag @pin.image %>
			<p class="pin_text content"><%= @pin.content %> - <%= @pin.author %></p>
		  <hr style="margin: 10px"></hr>
		  <p class="pin_text"><strong>Category: <%= @pin.category %></strong> - 
				<% if (current_user == @pin.user) || (current_user.admin) %>
				  	<%= link_to 'Edit', edit_pin_path(@pin) %>
				<% end %>
			</p>
			<%= link_to 'Your Profile', current_user %>
		</div>
	</div>
</div>

app/views/static_pages/_home.html.erb
<% provide(:title, 'QuoteWhat') %>

<!-- Full Page Image Header Area -->
<div id="top" class="header">
  <div class="vert-text full_page">
    <h1>Don't Remember a Quote?</h1>
    <h3><em>We</em> Help You Store It, <em>You</em> Keep On Changing</h3>
    <div class="row">
      <div class="container search-bar">
        <div class="col-md-8 col-md-offset-2">
          <%= form_tag(pins_path, :method => "get", id: "search-form") do %>
            <div class="input-group">
              <%= text_field_tag :search, params[:search], class: "form-control search-bar", placeholder: "Search Quotes, Category, Author" %>
              <div class="input-group-btn">
                <button class="btn btn-lg btn-default search-btn" type="submit">Search</button>
                <%= link_to "Sign In Now", new_user_session_path, class: "btn btn-primary btn-lg" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Services -->
<div id="services" class="services">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3 text-center">
        <h2>- You Can Do Several Things -</h2>
        <hr style="border-top: solid 1px black">
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 text-center">
        <img src="https://dl.dropboxusercontent.com/u/21093381/quotewhat/network-step1.jpg" class="img-thumbnail img-responsive" alt="">
        <h4><span>1.</span> Create Your Own Page</h4>
        <p>You can start storing Quotes and Picture Quote on your own profile!  You will no longer forget a quote.</p>
      </div>
      <div class="col-md-4 text-center">
        <img src="https://dl.dropboxusercontent.com/u/21093381/quotewhat/network-step2.jpg" class="img-thumbnail img-responsive" alt="">
        <h4><span>2.</span> Search For a Quote</h4>
        <p>In Need for a quote?  No problem, just type in a keyword, author, or even a category and we will search for a quote for you!</p>
      </div>
      <div class="col-md-4 text-center">
        <img src="https://dl.dropboxusercontent.com/u/21093381/quotewhat/network-step3.jpg" class="img-thumbnail img-responsive" alt="">
        <h4><span>3.</span> Follow Other People's Page</h4>
        <p>Are there people that you feel their quote are inspiring, funny, heartwarming, whatever makes you happy.  Follow them!</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 text-center">
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
      </div>
      <div class="col-md-4 text-center">
        <a href="#top" class="btn btn-lg btn-default">Search</a>
      </div>
      <div class="col-md-4 text-center">
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>
  </div>
</div>
<!-- /Services -->

<!-- Callout -->
<div class="callout">
  <div class="callout-text">
    <h2><em>"TravelFig is a great place for me to write my travel stories and recommendations.  It is also easy for me to find other relevant travel itineraries."</em></h2>
    <h3>- Member, San Francisco</h3>
  </div>
</div>
<!-- /Callout -->

<!-- Call to Action -->
<div class="call-to-action">
  <div class="container">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h3>Don't Hesitate Anymore!  Contribute Your Favorite Quote!</h3>
        <a href="/users/sign_up" class="btn btn-lg btn-default">Sign Up</a>
        <a href="#top" class="btn btn-lg btn-primary">Back Top</a>
      </div>
    </div>
  </div>
</div>
<!-- /Call to Action -->

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<!-- About Us Banner -->
<div id="aboutheader">
  <div id="aboutheader-text">
    <h1>We're Passionate About <span><em>Travel</em></span> and <span><em>Sharing</em></span></h1>
  </div>
</div>
<!-- /About Us Banner -->

<!-- About Us Content -->
<div id="aboutcontent">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<img class="img-rounded img-responsive" src="https://dl.dropboxusercontent.com/u/21093381/quotewhat/about-description.jpg">
			</div>
			<div class="col-md-8">
				<h1>About TravelFig</h1>
				<h4>Try-hard seitan DIY, bitters flannel Schlitz skateboard lo-fi readymade jean shorts selvage Tonx Godard Wes Anderson ugh. Seitan Thundercats twee 8-bit flexitarian fingerstache fanny pack messenger bag master cleanse, Bushwick tofu asymmetrical slow-carb pork belly. Selvage wolf trust fund, try-hard bespoke artisan High Life. Readymade selfies Pitchfork, chambray retro tousled PBRB tote bag squid small batch chia pop-up yr. Cred cardigan scenester, leggings cliche tofu Blue Bottle tattooed pug street art DIY hella Terry Richardson. Wes Anderson organic Bushwick, semiotics try-hard authentic pug stumptown gluten-free hoodie brunch American Apparel scenester fap hella. Bicycle rights freegan gastropub, four loko cred post-ironic Terry Richardson McSweeney's you probably haven't heard of them selvage messenger bag.</h4>
			</div>
		</div>
	</div>
</div>
<!-- /About Us Content -->

<!-- Team Profiles -->
<div id="teamprofile">
	<div class="container">
		<div class="row">
			<div class="col-md-4">
				<img class="img-circle img-responsive" src="https://dl.dropboxusercontent.com/u/21093381/quotewhat/about-profile.jpg">
			</div>
			<div class="col-md-8">
				<h2>Charles Hsieh, Founder</h2>
				<h4>Asymmetrical vegan Tumblr, meggings selvage occupy PBR pop-up Godard direct trade single-origin coffee sartorial locavore try-hard fixie. Cliche craft beer typewriter, aesthetic gluten-free vinyl Williamsburg Echo Park lomo. Wolf lomo Godard sriracha American Apparel ethnic, kitsch +1 Shoreditch High Life fanny pack viral PBR. Banh mi leggings keffiyeh banjo, freegan butcher tousled pop-up art party drinking vinegar deep v lo-fi. Odd Future gastropub you probably haven't heard of them, bicycle rights Neutra fap banjo selfies roof party mustache McSweeney's Marfa sustainable flannel tousled. IPhone chia readymade, hoodie cray sartorial distillery. High Life street art authentic umami, hoodie organic disrupt pickled Pitchfork art party beard Bushwick.</h4>
			</div>
		</div>
	</div>
</div>
<!-- /Team Profile -->

app/views/users/show.html.erb
<% provide(:title, 'Your Profile') %>

<div class="profileheader">
	<%= image_tag @user.avatar.url(:thumb), class: "profileheader-image img-responsive" %>
		<h2><%= @user.first_name %> <%= @user.last_name %></h2>
</div>
<ul class="nav nav-tabs nav-justified user-profile" id="userTab">
	<li class="active"><a href="#passport" data-toggle="tab">My Passport</a></li>
	<li><a href="#travel_plans" data-toggle="tab">Travel Plans</a></li>
	<li><a href="#destination_wishlist" data-toggle="tab">Destination Wishlist</a></li>
</ul>	
<div class="tab-content">
  <div class="tab-pane fade active in" id="passport">
  	<div id="isotope-container">
		  <%= render @pins %>
		</div>
		<%= will_paginate @pins %>
  </div>
  <div class="tab-pane fade" id="travel_plans">
  	<div id="isotope-container">
		  <%= render @pins %>
		</div>
		<%= will_paginate @pins %>
  </div>
  <div class="tab-pane fade" id="destination_wishlist">
  	<div id="isotope-container">
		  <%= render @pins %>
		</div>
		<%= will_paginate @pins %>
  </div>
</div>